name: build
on:
    push:
        paths-ignore:
            - "**/README.md"

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
jobs:
    unit-tests:
        name: CI Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                 distribution: 'oracle'
                 java-version: '18'
            - name: Run tests
              run: ./gradlew test
